Qbox-project/qbx_medical

- client/main.lua
- moved the variable BodyParts over
- introduced exports to mutate and read BodyParts
- snuck in MakePedLimp since it relies on BodyParts and nothing else
- renaming ResetMajorInjuries to ResetMinorInjuries
> feat(client/main): BodyParts migration

- client/dead.lua
- client/main.lua
- modules/hooks/server.lua
- server/main.lua
- created an event hook for respawn so other resources can override behavior to deny the respawn. This could be done to implement an entirely different respawn, or just small things like denying respawn if other players are nearby.
> feat: respawn migration and respawn event hook

- client/dead.lua
- client/laststand.lua
- client/main.lua
- client/setdownedstate.lua
- config.lua
- trigger a server event for other resources to act on when player is put into last stand state
- introduce export 'disableRespawn' to replace existing check to prevent respawning while in a hospital bed. Now qbx-ambulancejob can call disableRespawn when a player is put into a bed.
> feat(client): allow respawn migration

- client/dead.lua
as we can see we are referencing `qb-policejob` for the `IsHandcuffed()` export which is incorrect because we are working with `qbx-policejob` now.
> chore(qbx-medical/cl): reference `qbx-` and not `qb-` for policejob

- client/setdownedstate.lua
fixes:[ ^1SCRIPT ERROR: @ox_lib/requestAnimDict/client.lua:13: attempted to load invalid animDict 'vehicleDict'^7](https://github.com/Qbox-project/qbx-medical/blob/42e0acae2d3f461e72d4d4694bd7dc128b211121/client/setdownedstate.lua#L8)
> fix(anim): Fix anim dict calling an incorrect dictionary

- client/load-unload.lua
- This seems to have an effect, as it appears it is triggered in different scenarios causing the ped to die or heal/reset statuses.
> fix(load-unload): remove player unload

- client/damage/damage-effects.lua
- client/damage/damage.lua
- client/main.lua
Not needed anymore since both of these can be derived from the bodypart the injury is in
> refactor: remove label and body part key from injury

- client/damage/damage-effects.lua
- client/damage/damage.lua
- client/main.lua
- client/wounding.lua
I made the following observations
- Only one injury is allowed per body part
- An injury only holds a severity
- a bodypart has a severity that is kept in sync with the bodypart's injuries' severity
This leads to the conclusion that injuries can be removed in favor of using the bodypart's severity directly to make the code simpler.
> refactor: remove injuries

- client/damage/damage.lua
- client/main.lua
- server/main.lua
- changed to a set (table<hash, boolean>) for more efficient lookups
- renamed variable to be more descriptive
- removing client side exports for reviving as this should originate from the server
- syncing less data to the server (only when a new weapon damages a player it sends that one only instead of all previous weapons)
- removed unneeded callbacks. i.e. the server asks the client to revive themselves, and clears the set rather than have the client callback to the server to do it
> refactor: weapons that damage player synced more efficiently with server

- client/damage/damage-effects.lua
- client/damage/damage.lua
- client/main.lua
- client/wounding.lua
- config.lua
- server/main.lua
- move body parts to config (static fields)
- split off injuries from body parts and represent as map of body part key to severity to represent the structure that a bodypart has a severity that is changed. A bodypart not being in the Injuries table means that it isn't injured
> refactor: move static body part fields to config

- client/dead.lua
- client/laststand.lua
- client/main.lua
- server/main.lua
- shared/main.lua
- updating player's metadata for isDead and inLaststand when death state changes
> refactor: using death state as a statebag

- client/damage/apply-damage-effects.lua
- client/damage/damage.lua
- client/dead.lua
- client/laststand.lua
- client/load-unload.lua
- client/main.lua
- client/setdownedstate.lua
- client/wounding.lua
- server/main.lua
- Standardize `'` over `"`
- Proper usage and implementation of ox_lib's caching features
- Addition of 5000ms timeouts added to all ox_lib's streaming features
- Addition of constants for `exports.qbx_core:GetWeapons()`
- Replacment of the old ox_lib notifys to the new core notifies
- Other minor style fixes and changes
> refactor: proper ox implementation and style fixes

- client/load-unload.lua
If player logs out with less than 200hp and logs back in, they will be back at 200hp. This change fixe this issue
It's my first contribution, first pull request and i learn developpement so sorry if my contribution is not good
> fix: restoring health level when logging in

- server/main.lua
The isDead statebag is used by pma-voice to disable the radio. (it could also be used for other things i guess)
> Replicate isDead to statebag

- client/laststand.lua
Fixed the issue where the player gets stuck in the ragdoll animation and never go into the last stand state unless they're melee attacked. Tested it about 30 times, and it works.
> fix(client/laststand): player not always going to laststand state

- client/laststand.lua
Should help with frozen ragdoll states, most cases where ragdoll state was frozen the weapon was equipped.
> fix(client/laststand): trigger disarm event in StartLaststand

- .gitignore
- client/damage/damage.lua
- client/dead.lua
- client/laststand.lua
- client/load-unload.lua
- client/main.lua
- client/setdownedstate.lua
- config/client.lua
- server/main.lua
- proper ox_lib callbacks
- setting inventory to busy while down
- fixing the allow respawn exports
- fixing some weirdness around the timing of holding e to respawn
- using metadata for handcuff authority instead of policejob export
- handle case where a weapon isn't in the shared/weapons
- introduce config.deathTime and use it
- a few renames and removal of an export that isn't needed
> fix: miscl fixes

- client/main.lua
- server/main.lua
Fixes #94 though I feel these events might be exploitable
> fix: txAdmin Heal Everyone functionality

- client/laststand.lua
StartLastStand() is invoked when the player takes damage, however waits for the player to stop moving to actually change the state bag value. Thus if the player takes further damage while rag dolling, StartLastStand() is triggered again. This results in multiple threads being created which count down the counter.
The solution in this PR is to acquire an exclusive lock so that StartLastStand() cannot be running in two separate threads.
An alternative solution would be to move the waiting for the player to stop moving to the call sites of StartLastStand() and instead of using a lock, just check the state bag value isn't already in last stand.
> fix(client/laststand): counting down at double speed

- config/client.lua
- config/shared.lua
shared.lua was missing a few types,
client.lua had "StaggerArea" class which wasn't applied to anything
> Fix: Types not being applied
